package com.edulead.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
import com.edulead.server.model.Lead;
import com.edulead.server.model.Lead.LeadStatus;
import com.edulead.server.model.Lead.LeadScore;

import com.edulead.server.repository.LeadRepository;
import com.edulead.server.repository.UserRepository;
import com.edulead.server.repository.FollowUpRepository;
import com.edulead.server.model.User;
import com.edulead.server.model.FollowUp;
import org.springframework.boot.CommandLineRunner;

import org.springframework.context.annotation.Bean;

import java.time.LocalDateTime;

@SpringBootApplication(scanBasePackages = "com.edulead")
public class EduleadCrmServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(EduleadCrmServerApplication.class, args);
	}

	@Bean
	public CommandLineRunner demo(LeadRepository repository, UserRepository userRepository,
			FollowUpRepository followUpRepository) {
		return (args) -> {
			if (userRepository.count() == 0) {
				User admin = userRepository.save(new User("Admin Lead", "admin@edulead.com", "ADMIN", "ACTIVE"));
				User karan = userRepository
						.save(new User("Karan Singh", "karan.s@edulead.com", "COUNSELLOR", "ACTIVE"));

				if (repository.count() == 0) {
					Lead l1 = repository
							.save(new Lead("Rahul Sharma", "rahul@example.com", "+91 98765 43210", "Facebook Ads",
									LeadStatus.NEW, LeadScore.HOT, "Interested in B.Tech", LocalDateTime.now()));
					Lead l2 = repository.save(new Lead("Sneha Kapoor", "sneha@example.com", "+91 98221 12233",
							"Google Search", LeadStatus.CONTACTED, LeadScore.WARM, "Needs follow up",
							LocalDateTime.now().minusHours(1)));
					Lead l3 = repository.save(new Lead("Amit Verma", "amit.v@example.com", "+91 77665 54433",
							"Direct Walk-in", LeadStatus.FOLLOW_UP, LeadScore.COLD, "Requested brochure",
							LocalDateTime.now().minusHours(4)));

					l1.setAssignedTo(karan);
					l2.setAssignedTo(karan);
					repository.save(l1);
					repository.save(l2);

					followUpRepository.save(new FollowUp(l1, "Send B.Tech Brochure", LocalDateTime.now().plusHours(2),
							"HIGH", "PENDING"));
					followUpRepository.save(new FollowUp(l2, "Fee Structure Discussion",
							LocalDateTime.now().plusHours(4), "MEDIUM", "PENDING"));
				}
			}
		};
	}

}
